notifications:
  slack:
    rooms:
      - travisnotific-r1j8011:vSTulN5f4aIY18sZ46Og7kcp
      - travisnotific-r1j8011:7s2QnoWHP8Cvz5ABZeFjvllX
      - geekshubs:S32At4pC3DX58sqtloCFQXyz#gh-un-it-recruitment-candis
    on_success: always
    on_failure: always
    template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
    rooms: geekshubs:S32At4pC3DX58sqtloCFQXyz#gh-un-it-recruitment-candis-failures
    on_success: never
    on_failure: always
    template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
language: python
dist: trusty
cache: false
python:
 - "3.6"
install: pip install -e .
script: pytest
